name: Generate Image

on:
  push:
    branches: [main]
  schedule:
    - cron: 0 0/1 * * *

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          run_install: false

      - name: Install deps
        run: pnpm i

      - name: Prepare Bgm Data
        run: pnpm sync:bgm
        working-directory: ./mahiro

      - name: Prepare HTML
        run: pnpm build
        working-directory: ./render/common

      - name: Generate Image
        run: pnpm copy && pnpm start --generate --compress
        working-directory: ./server

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "server/output.png"

      - name: Move Image
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          mkdir -p output
          mv server/output.png output/output.png

      - name: Deploy
        if: steps.check_files.outputs.files_exists == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./output
